name: Rails + React CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Manish@2000
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Manish@2000
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      DATABASE_URL: postgres://postgres:Manish@2000@localhost:5432/react_demo_development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      # Setup Node.js + Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install Yarn deps
        run: yarn install --frozen-lockfile

      - name: Install Ruby gems
        run: bundle install --jobs 4 --retry 3

      - name: Set up DB
        run: |
          bundle exec rails db:create db:migrate --trace

      - name: Precompile assets (Rails + React build)
        run: bundle exec rails assets:precompile
